name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
      - name: Disable git safe directory checks
        run: git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          submodules: recursive

      - name: Checkout keymap
        uses: actions/checkout@v3
        with:
          path: keyboards/gmmk/pro/rev1/ansi/keymaps/${{ github.actor }}

      - name: Build firmware
        run: qmk compile -kb "gmmk/pro/ansi/rev1" -km "${{ github.actor }}"

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: gmmk_pro_rev1_ansi_${{ github.actor }}
          path: |
            *.hex
            *.bin
            *.uf2
